---
# This is a draft of the play used to script an automated Ansible
# deployment of a home security camera with Raspberry Pi 2 Model B / Raspbian Lite
# using the motioneye front-end for the motion daemon.
- name: Install Camera
  hosts: rpi2
  gather_facts: yes
  remote_user: pi
  become: yes
  vars:
    boot_config: {'start_x': '1', 'gpu_mem': '192', 'disable_camera_led': '1'}
  tasks:     
    - name: <1/25> Updating system...
      apt: update_cache=yes
      
    - name: <2/25> Upgrading system...
      apt: upgrade=full
      
    - name: <3/25> Adding boot settings to enable raspberry pi on-board camera module...
      lineinfile: line='{{ item.key }}={{ item.value }}'
        dest=/boot/config.txt
        regexp="^{{ item.key }}="
      with_dict: '{{ boot_config }}'
      register: _boot_config
      
    - name: <4/25> Adding raspberry camera kernel module...
      lineinfile:
        dest: /etc/modules
        regexp: 'bcm2835-v4l2'
        line: 'bcm2835-v4l2'
        state: present

    - name: <5/25> Installing dependencies (ffmpeg)
      apt:
        name: ffmpeg

    - name: <6/25> Installing dependencies (v4l-utils)
      apt:
        name: v4l-utils

    - name: <7/25> Downloading dependencies (motion)...
      get_url:
        url: https://github.com/Motion-Project/motion/releases/download/release-4.1.1/pi_stretch_motion_4.1.1-1_armhf.deb  
        dest: /home/pi/pi_stretch_motion_4.1.1-1_armhf.deb

    - name: <8/25> Installing dependencies (motion dependencies)...
      apt:
        name: '{{packages}}'
      vars:
        packages:
          - libmariadbclient18
          - libpq5

    - name: <9/25> Installing motion...
      command: dpkg -i pi_stretch_motion_4.1.1-1_armhf.deb

    - name: <10/25> Installing dependencies (motioneye dependencies)...
      apt:
        name: '{{packages}}'
      vars:
        packages:
          - python-pip
          - python-dev
          - libssl-dev
          - libcurl4-openssl-dev
          - libjpeg-dev
          - libz-dev

    - name: <11/25> Installing motioneye...
      command: pip install motioneye
      
    - name: <12/25> Creating motioneye configuration directory...
      file: path=/etc/motioneye state=directory

    - name: <13/25> Copying motioneye default configuration...
      command: cp /usr/local/share/motioneye/extra/motioneye.conf.sample /etc/motioneye/motioneye.conf
      
    # This should be done by Ansible directly replacing parameters in the config files. 
    # Doing it this way for testing purposes first.
    - name: <14/25> Applying provided configuration to motioneye...
      copy: 
        src: "{{ item }}"
        dest: /etc/motioneye
        owner: pi
      with_fileglob:
        - motioneye-config/*
    
    - name: <15/25> Replacing motioneye templates with localized version...
      copy:
        src: "{{ item }}"
        dest: /usr/local/lib/python2.7/dist-packages/motioneye/templates
        owner: pi
      with_fileglob:
        - motioneye-templates/*

    - name: <16/25> Replacing motioneye CSS...
      copy:
        src: "{{ item }}"
        dest: /usr/local/lib/python2.7/dist-packages/motioneye/static/js
        owner: pi
      with_fileglob:
        - motioneye-static/css/*

    - name: <17/25> Replacing motioneye JS...
      copy:
        src: "{{ item }}"
        dest: /usr/local/lib/python2.7/dist-packages/motioneye/static/js
        owner: pi
      with_fileglob:
        - motioneye-static/js/*

    - name: <18/25> Deleting original fonts...
      command: sudo rm -f /usr/local/lib/python2.7/dist-packages/motioneye/static/fnt/mavenpro-*

    - name: <19/25> Adding fonts with Cyrilic support...
      copy:
        src: "{{ item }}"
        dest: /usr/local/lib/python2.7/dist-packages/motioneye/static/fnt
        owner: pi
      with_fileglob:
        - motioneye-static/fnt/*

    - name: <20/25> Creating motioneye data state directory...
      file: path=/var/lib/motioneye state=directory

    - name: <21/25> Adding motioneye service...
      command: cp /usr/local/share/motioneye/extra/motioneye.systemd-unit-local /etc/systemd/system/motioneye.service

    - name: <22/25> Reloading systemd manager configuration...
      command: systemctl daemon-reload
      
    - name: <23/25> Enabling motioneye...
      command: systemctl enable motioneye
      
    - name: <24/25> Starting motioneye...
      command: systemctl start motioneye
      
    - name: <25/25> Install additional utilities...
      apt: pkg={{item}} state=present
      with_items:
        - vim
        - git

    - name: <Rebooting> Playbook complete! Thanks for playing =)
      shell: sleep 2 && shutdown -r now "Ansible reboot triggered"
      async: 1
      poll: 0
      ignore_errors: true
