---
- name: Replace MotionEye Static Files
  hosts: rpi2
  gather_facts: no
  remote_user: pi
  become: yes
  tasks:     
    - name: <1/8> Updating system...
      apt: update_cache=yes
      
    - name: <2/8> Upgrading system...
      apt: upgrade=full

    - name: <3/8> Replacing motioneye CSS...
      copy:
        src: "{{ item }}"
        dest: /usr/local/lib/python2.7/dist-packages/motioneye/static/css
        owner: pi
      with_fileglob:
        - motioneye-static/css/*

    - name: <4/8> Replacing motioneye JS...
      copy:
        src: "{{ item }}"
        dest: /usr/local/lib/python2.7/dist-packages/motioneye/static/js
        owner: pi
      with_fileglob:
        - motioneye-static/js/*

    - name: <5/8> Replacing motioneye logos and images...
      copy:
        src: "{{ item }}"
        dest: /usr/local/lib/python2.7/dist-packages/motioneye/static/js
        owner: pi
      with_fileglob:
        - motioneye-static/js/*
        
    - name: <6/8> Replacing motioneye templates...
      copy:
        src: "{{ item }}"
        dest: /usr/local/lib/python2.7/dist-packages/motioneye/templates
        owner: pi
      with_fileglob:
        - motioneye-templates/*

    - name: <7/8> Reloading systemd manager configuration...
      command: systemctl daemon-reload
      
    - name: <8/8> Restarting motioneye...
      command: systemctl restart motioneye
