- name: install motion dependencies
  apt:
    name: '{{packages}}'
  vars:
    packages:
      - ffmpeg
      - v4l-utils
      - libmariadbclient18
      - libpq5

- name: download motion
  get_url:
    url: https://github.com/Motion-Project/motion/releases/download/release-4.1.1/pi_stretch_motion_4.1.1-1_armhf.deb
    dest: /home/pi/pi_stretch_motion_4.1.1-1_armhf.deb
    
- name: install motion
  command: dpkg -i pi_stretch_motion_4.1.1-1_armhf.deb

- name: copy motion default configuration
  template:
    src: ../templates/motion.conf
    dest: /etc/motioneye/motion.conf

- name: copy motion thread configuration
  template:
    src: ../templates/thread-1.conf
    dest: /etc/motioneye/thread-1.conf
