# Ansible task to style BabaGinka's front end.
# -----------------------------------------------------------------------------
#
# 

- name: <Replace static files> Add cyrillic fonts for motioneye
  copy:
    src: "{{ item }}"
    dest: /usr/local/lib/python2.7/dist-packages/motioneye/static/fnt
    owner: pi
  with_fileglob:
    - ../files/fnt/*

- name: <Replace static files> Replace motionEye CSS 1
  template:
    src: ../templates/css/ui.css
    dest: /usr/local/lib/python2.7/dist-packages/motioneye/static/css/ui.css

- name: <Replace static files> Replace motionEye CSS 2
  template:
    src: ../templates/css/main.css
    dest: /usr/local/lib/python2.7/dist-packages/motioneye/static/css/main.css

- name: <Replace static files> Replace motionEye CSS 3
  template:
    src: ../templates/css/frame.css
    dest: /usr/local/lib/python2.7/dist-packages/motioneye/static/css/frame.css
