# Ansible task to install motionEye - a web frontend for the motion daemon.
# -----------------------------------------------------------------------------
#
# motionEye is developed by Calin Crisan.
# More info at https://github.com/ccrisan/motioneye

- name: <Install motionEye> Install motionEye dependencies
  apt:
    name: '{{packages}}'
  vars:
    packages:
      - python-pip
      - python-dev
      - libssl-dev
      - libcurl4-openssl-dev
      - libjpeg-dev
      - libz-dev

- name: <Install motionEye> Install motionEye module
  command: pip install motioneye
  
- name: <Install motionEye> Prepare motionEye configuration directory
  file: path=/etc/motioneye state=directory

- name: <Install motionEye> Prepare motionEye media directory
  file: path=/var/lib/motioneye state=directory

- name: <Install motionEye> Add motion default configuration
  template:
    src: ../templates/motion.conf
    dest: /etc/motioneye/motion.conf

- name: <Install motionEye> Add motionEye default configuration
  template:
    src: ../templates/motioneye.conf
    dest: /etc/motioneye/motioneye.conf

- name: <Install motionEye> Add motion camera configuration
  template:
    src: ../templates/camera-1.conf
    dest: /etc/motioneye/camera-1.conf

- name: <Install motionEye> Add user UI preference configuration
  template:
    src: ../templates/prefs.json
    dest: /etc/motioneye/prefs.json

- name: <Install motionEye> Add motionEye service
  command: cp /usr/local/share/motioneye/extra/motioneye.systemd-unit-local /etc/systemd/system/motioneye.service

- name: <Install motionEye> Reload systemd manager configuration
  command: systemctl daemon-reload
  
- name: <Install motionEye> Enable motioneye service
  command: systemctl enable motioneye
  
- name: <Install motionEye> Start motioneye service
  command: systemctl start motioneye
