# Ansible task to install motion - a video signal monitoring program
# -----------------------------------------------------------------------------
#
# More info at https://github.com/Motion-Project

- name: <Install motion> Install motion dependencies
  apt:
    name: '{{packages}}'
  vars:
    packages:
      - ffmpeg
      - libmariadb3
      - libpq5
      - libmicrohttpd12

- name: <Install motion> Download motion
  get_url:
    url: https://github.com/Motion-Project/motion/releases/download/release-4.2.2/pi_buster_motion_4.2.2-1_armhf.deb
    dest: /home/pi/pi_buster_motion_4.2.2-1_armhf.deb
    
- name: <Install motion> Install motion
  command: dpkg -i pi_buster_motion_4.2.2-1_armhf.deb
