# Ansible task to style BabaGinka's front end.
# -----------------------------------------------------------------------------
#
# This file contains a sequence of tasks to style the motionEye frontend.

- name: <Replace static files> Add cyrillic fonts for motioneye
  copy:
    src: "{{ item }}"
    dest: /usr/local/lib/python2.7/dist-packages/motioneye/static/fnt
    owner: pi
  with_fileglob:
    - ../files/fnt/*

- name: <Replace static files> Replace motionEye CSS
  copy:
    src: "{{ item }}"
    dest: /usr/local/lib/python2.7/dist-packages/motioneye/static/css
    owner: pi
  with_fileglob:
    - ../files/css/*

- name: <Replace static files> Replace motionEye images
  copy:
    src: "{{ item }}"
    dest: /usr/local/lib/python2.7/dist-packages/motioneye/static/img
    owner: pi
  with_fileglob:
    - ../files/img/*
