# Ansible task to install motion - a video signal monitoring program
# -----------------------------------------------------------------------------
#
# More info at https://github.com/Motion-Project

- name: <Install motion> Install motion dependencies
  apt:
    name: '{{packages}}'
  vars:
    packages:
      - ffmpeg
      - v4l-utils
      - libmariadbclient18
      - libpq5

- name: <Install motion> Download motion
  get_url:
    url: https://github.com/Motion-Project/motion/releases/download/release-4.1.1/pi_stretch_motion_4.1.1-1_armhf.deb
    dest: /home/pi/pi_stretch_motion_4.1.1-1_armhf.deb
    
- name: <Install motion> Install motion
  command: dpkg -i pi_stretch_motion_4.1.1-1_armhf.deb
