# Ansible task to install commonly used packages
# -----------------------------------------------------------------------------
#

- name: installing additional utilities
  apt:
    name: '{{ packages }}'
  vars:
    packages:
      - vim
      - git

