---
- name: Configure BabaGinka
  hosts: rpi2
  gather_facts: no
  remote_user: pi
  become: yes
  tasks:     

    - name: <motion.conf> Adding username
      lineinfile:
        dest: /etc/motioneye/motion.conf
        regexp: '^# @normal_username'
        line: '# @normal_username ginka'

    - name: <motioneye.conf> Modify to listen to port 80
      lineinfile:
        dest: /etc/motioneye/motioneye.conf
        regexp: '^port'
        line: 'port 80'

    - name: <thread-1.conf> Stopping motion detection by default
      lineinfile:
        dest: /etc/motioneye/thread-1.conf
        regexp: '^# @motion_detection'
        line: '# @motion_detection off'

    - name: <thread-1.conf> Naming the camera
      lineinfile:
        dest: /etc/motioneye/thread-1.conf
        regexp: '^# @name'
        line: '# @name Ginka'

    - name: <thread-1.conf> Setting image width
      lineinfile:
        dest: /etc/motioneye/thread-1.conf
        regexp: '^width'
        line: 'width 1280'

    - name: <thread-1.conf> Setting image height
      lineinfile:
        dest: /etc/motioneye/thread-1.conf
        regexp: '^height'
        line: 'height 1080'

    - name: <thread-1.conf> Setting image threshold
      lineinfile:
        dest: /etc/motioneye/thread-1.conf
        regexp: '^threshold'
        line: 'threshold 64225'

    - name: <thread-1.conf> Setting stream maximum framerate
      lineinfile:
        dest: /etc/motioneye/thread-1.conf
        regexp: '^stream_maxrate'
        line: 'stream_maxrate 10'

    - name: <thread-1.conf> Setting framerate
      lineinfile:
        dest: /etc/motioneye/thread-1.conf
        regexp: '^framerate'
        line: 'framerate 10'

    - name: Reloading systemd manager configuration...
      command: systemctl daemon-reload
      
    - name: Restarting motioneye...
      command: systemctl restart motioneye
