---
- name: Install Baba Ginka
  hosts: rpi2
  gather_facts: yes
  remote_user: pi
  become: yes

  vars:
    boot_config: {'start_x': '1', 'gpu_mem': '192', 'disable_camera_led': '1'}

  vars_prompt:

    - name: HOSTNAME
      prompt: "Please provide a hostname for the camera unit"
      private: no

    - name: WLAN_SSID
      prompt: "Wireless network to connect to"
      private: no

    - name: WLAN_PASS
      prompt: "Wireless network password"
      private: yes

    - name: ADMIN_USERNAME
      prompt: "Please enter an user name for the admin account"
      default: "admin"
      private: no

    - name: ADMIN_PASSWORD
      prompt: "Please enter a password for the admin account"
      private: yes

    - name: NORMAL_USERNAME
      prompt: "Please enter a user name for the user account"
      default: "ginka"
      private: no

    - name: NORMAL_PASSWORD
      prompt: "Please enter a password for the user account"
      private: yes

    - name: TCP_PORT
      prompt: "Port to listen to"
      default: "80"
      private: no

    - name: TIMEZONE
      prompt: "Timezone the camera will operate in"
      default: "Europe/Sofia"

  tasks:
    - include_tasks: tasks/raspbian_common.yml

    - include_tasks: tasks/raspbian_cameramodule.yml

    - include_tasks: tasks/raspbian_add_utils.yml

    - include_tasks: tasks/motion_install.yml

    - include_tasks: tasks/motioneye_install.yml

    - include_tasks: tasks/motioneye_style.yml

    - include_tasks: tasks/motioneye_translate.yml

    - name: Playbook complete! Restarting Raspberry Pi
      shell: sleep 2 && shutdown -r now "Ansible reboot triggered"
      async: 1
      poll: 0
      ignore_errors: true
